### ISSUE TITLE
library Works ?

### ISSUE THREAD

**Issue by h2soheili** [pusheco/pushe-react-native#1]
thanks to this awesome work.
i followed all steps in docs and even compared with `https://github.com/zo0r/react-native-push-notification ` for AndroidManifist.xml .  required  permissions . but my app isn'n in dashboard.
i tested in several device and emulator (play service installed)
and properly called `Pushe.initialize(true)`

 possible module problem in react native ?
 any advice ?

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
لطفا مشکلتون رو شرح بدید.

در مورد خطایی که دارید هم جزئیاتی ارائه بدید

</div>
