### ISSUE TITLE
دریافت  callback زمانی که اپ بسته است

### ISSUE THREAD

**Issue by psobhanlo** [pusheco/pushe-react-native#10]
زمانی که اپ باز هست وقتی پوش میفرستم custom content  رو تو
debuger
یا
 react native log-android
adb logcat *:S ReactNative:V ReactNativeJS:V
اما وقتی که اپ میاد تو  backgorund
 بهم لاگی نشون نمیده

ایا این به دلیل اینه که دیباگر اپ رو نمیتونه زمانی که تو بک گرانده  اطلاعات بگیره؟؟؟
یا کلا زمانی که اپ بسته است نمیشه دیتایی  json رو دریافت کرد؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
این مورد تست شده و کار می‌کنه

</div>

[Notification callback documentation for react native](http://docs.pushe.co/docs/react-native/notification-events)
