### ISSUE TITLE
Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

### ISSUE THREAD

**Issue by mahdipc** [pusheco/pushe-react-native#12]
سلام. بعداز نصب پوشه همچین خطایی بهم میده. ممنون میشم راهنمایی بفرمایید.

> `

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
190 actionable tasks: 2 executed, 188 up-to-date
D8: Cannot fit requested classes in a single dex file (# methods: 85932 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
D8: Cannot fit requested classes in a single dex file (# methods: 85932 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  The number of method references in a .dex file cannot exceed 64K.
`

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام خطای شما طبق استک‌تریس‌تون به این مورد خلاصه می‌شه:

</div>

```
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
The number of method references in a .dex file cannot exceed 64K.
```

<div dir='rtl'>

شما باید **مالتی‌دکس** رو توی پروژتون فعال کنید.

[How to enable multidex in reactNative project](https://stackoverflow.com/a/56875424/6678991)

</div>

**Comment by mahdi-malv** [comment]
Feel free to reopen if the problem still exists and the solution was not helpful
