### ISSUE TITLE
pushe registery

### ISSUE THREAD

**Issue by kianaaa76** [pusheco/pushe-react-native#14]
سلام. من از پوش نوتیفیکیشن پوشه استفاده میکنم ولی بعد از کار های نصب و راه اندازی هنوز رجیستر نشده. مشکل از چی میتونه باشه؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

در صورتی که نصب ثبت نمیشه باید ابتدا مستندات رو بررسی کنید و در بخش خطاها به دنبال خطای مشابه خودتون توی لاگ‌خروجی برنامه بگردید.

در صورتی که مشکل رو پیدا نکردید توی issue های بسته‌ یا باز در گیتهاب بگردید و در صورتی که باز هم مورد مشابه وجود نداشت با ذکر جزئیات می‌تونید مشکل رو بیان کنید.

اما اگر مشکل خیلی حاد هست، یا قابل اشتراک‌گذاری در ریپو‌های عمومی نیست باید به پشتیبانی اطلاع بدید تا بررسی‌های لازم انجام بشه.


همچنین می‌تونید جزئیات رو به همین issue  اضافه کنید تا همکاران توسعه‌دهنده بررسی کنن
</div>

[**ReactNative FAQ**](https://docs.pushe.co/docs/react-native/errors)

[Support](https://console.pushe.co)

[All issues of repo](https://github.com/pusheco/pushe-react-native/issues?q=is%3Aissue+)
