### ISSUE TITLE
'pushe-react-native' is not in the npm registry.

### ISSUE THREAD

**Issue by h2soheili** [pusheco/pushe-react-native#2]
there in no pushe-react-native in npm repository.
please rename this repo or correct module name .

**Comment by amirhaa** [comment]
We were making some changes and now the latest version is published in the **npm** repository

**Comment by h2soheili** [comment]
could you publish version without new `androidx` changes.it is soon for us to ship androidx and jetifier.
we plan to stick in react-native 0.59.10 and build tools 28 , a little more due to some problems.

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
در نسخه‌ی بعدی این مشکل حل خواهد شد.
برای حل مشکل در این نسخه می‌تونید این مورد رو بررسی کنید:
https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries
</div>
