### ISSUE TITLE
Error in start app

### ISSUE THREAD

**Issue by arta7** [pusheco/pushe-react-native#20]
با سلام
بعد از نصب پوشه در نسخه 0.61.5 ریکت نیتیو با خطای زیر مواجه شدم.من فقط میخواستم پوشه در اپ نصب بشه و کار دیگه ای قرار نیست با آن انجام شود و طبق دستور العمل نصب پوشه در ریکت نیتیو پیش رفتم و متادیتا رو هم اضافه کردم ولی از هیچ یک از توابع ناتیفیکیشن در کارم استفاده نکردم ولی باز هم خطای زیر را میدهد.به نظر میرسد مشکل از سمت کدهای جاوا برنامه باشد.
قسمتی از متن ارور : 
attempt to invoke virtual method void co.pushe.plus.notification.pushenotificationListener()
on a null object reference

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
این فانکشن در توابع خود پلاگین استفاده شده.
باید مطمئن شید که پوشه به برنامه اضافه شده باشه. طبق این خطا ماژول نوتیفیکیشن وجود نداره.

آیا خطای دیگه‌ای هم چاپ میشه توی لاگ‌کت؟

</div>

**Comment by arta7** [comment]
<div dir='rtl'>

با سلام
علت این خطا برای این بوده است که کد meta-data درون تگ application قرار نگرفته بود و بعد از بررسی و مشاهده مستندات بخش اندروید استودیو این قسمت را درون تگ application قرار دادم و مشکل حل شد.اگر ممکن هست محل  دقیق استفاده از تگ meta-data که درون آن توکن پوشه قرار گرفته است را درون بخش مستندات react-native هم قرار دهید تا دوستان دیگر به مشکل نخورن.

</div>

**Comment by mahdi-malv** [comment]
https://github.com/pusheco/pushe-docs/pull/41

**Comment by mahdi-malv** [comment]
[**Pull request**](https://github.com/pusheco/pushe-docs/pull/41) created for **docs**.

**Comment by sinafbd** [comment]
+1

**Comment by sinafbd** [comment]
منم همین مشکلو دارم. متا دیتا هم داخل تگ اپلیکیشنه. چیکار کنم؟

**Comment by mahdi-malv** [comment]
@sinafbd 
ممنون می‌شم لاگ رو با جزئیات بیشتر بفرستید که ببینم قبلش چه اتفافی افتاده

**Comment by sinafbd** [comment]
اپ موقع باز شدن کرش می کنه. هیچ لاگی هیچ جا پیدا نمیکنم. لطفا راهنمایی کنیید اگر جایی چیزی باید بفرستم، بفرستم

**Comment by mahdi-malv** [comment]
@sinafbd 

<div dir='rtl'>

اگر بتونید یه نمونه از خروجی اپلیکیشن رو به ساپورت ارسال کنید من بررسی بیشتری خواهم داشت.
معمولا اگر مشکلی واسه ماژول اصلی پیش بیاد ماژول‌های دیگه نمیتونن کار کنن و هر تابعی هم از اون ماژول‌ها صدازده بشه خطا رخ میده (تو این کیس ماژول نوتیفیکیشن). لذا باید بفهمم چرا ماژول اصلی به مشکل خورده.
این لاگ توی لاگ اندروید نیتیو نمایش داده میشه و توی لاگ ری‌اکت نمیشه دیدش متاسفانه. برای همین یه نمونه اپ هم میتونه کمک کنه.

</div>

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

نسخه‌ی **2.4.1** تغییراتی توی این بخش داشته که به دیباگینگش کمک می‌کنه. در صورتی که این مشکل پیش میاد اون نسخه میتونه بهتر راهنمایی کنه.

</div>

[**pushe-react-native: 2.4.1**](https://www.npmjs.com/package/pushe-react-native/v/2.4.1)
