### ISSUE TITLE
App Crash on Start - RNPushe.java:483

### ISSUE THREAD

**Issue by xnimax** [pusheco/pushe-react-native#23]
سلام
من در هنگام نصب توی لاگ کت این ارور رو دارم در صورتی مانیفستم درسته و پکیج بدون خطا نصب شده.

11-02 14:11:22.640  5705  5800 E Pushe   : The Pushe service notification is not available. This either means you have provided an invalid Pushe Service name, Pushe was not initialized successfully or you have not added the Pushe service to your gradle dependencies.: ir.elipapp
11-02 14:11:22.640  5705  5800 E Pushe   : The Pushe service analytics is not available. This either means you have provided an invalid Pushe Service name, Pushe was not initialized successfully or you have not added the Pushe service to your gradle dependencies.: ir.elipapp
11-02 14:11:22.640  5705  5800 E Pushe   : The Pushe service PusheInAppMessaging is not available. This either means you have provided an invalid Pushe Service name, Pushe was not initialized successfully or you have not added the Pushe service to your gradle dependencies.: ir.elipapp
11-02 14:11:22.640  5705  5800 E Pushe   : The Pushe service notification is not available. This either means you have provided an invalid Pushe Service name, Pushe was not initialized successfully or you have not added the Pushe service to your gradle dependencies.: ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: Exception in native call: ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: java.lang.NullPointerException: Attempt to invoke virtual method 'void co.pushe.plus.notification.PusheNotification.setNotificationListener(co.pushe.plus.notification.PusheNotificationListener)' on a null object reference: ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at co.pushe.plus.RNPushe.initializeNotificationCallbacks(RNPushe.java:483): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at co.pushe.plus.RNPushe.<init>(RNPushe.java:74): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at co.pushe.plus.RNPushePackage.createNativeModules(RNPushePackage.java:17): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016): ir.elipapp
11-02 14:11:22.642  5705  5800 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764): ir.elipapp

**Comment by mahdi-malv** [comment]
Explained here #20
