### ISSUE TITLE
 Duplicate class : logback-android-1.1.1-9-runtime.jar & slf4j-simple-1.7.25.jar

### ISSUE THREAD

**Issue by peyman-hakemi** [pusheco/pushe-react-native#24]
after installing pushe-react-native my build get failed every time with this message

`Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class org.slf4j.impl.StaticLoggerBinder found in modules logback-android-1.1.1-9-runtime.jar (com.github.tony19:logback-android:1.1.1-9) and slf4j-simple-1.7.25.jar (org.slf4j:slf4j-simple:1.7.25)
  Duplicate class org.slf4j.impl.StaticMDCBinder found in modules logback-android-1.1.1-9-runtime.jar (com.github.tony19:logback-android:1.1.1-9) and slf4j-simple-1.7.25.jar (org.slf4j:slf4j-simple:1.7.25)
  Duplicate class org.slf4j.impl.StaticMarkerBinder found in modules logback-android-1.1.1-9-runtime.jar (com.github.tony19:logback-android:1.1.1-9) and slf4j-simple-1.7.25.jar (org.slf4j:slf4j-simple:1.7.25)`

when i delete pushe-react-native every thing is ok

what should i do ?

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام    
بنظر یه پلاگین دیگه‌ای لایبرری‌های خودش رو با گریدل اضافه نکرده. در صورتی که یه لایبرری بصورت فایل خام به برنامه اضافه شه و یه پلاگین دیگه همون لایبرری رو به صورت استاندارد با گریدل اضافه کنه، گریدل نمی‌تونه تشخیص بده اینا یکی هستن. لذا ارور خواهد داد.


من چون نمی‌دونم چه پلاگین‌هایی تو اپ شما استفاده شده می‌تونم ساجست کنم که اون لایبرری رو از پوشه جدا کنید. احتمال داره مشکل اینطوری حل شه:
</div>

1. Use latest version of `pushe-react-native`

2. Temporarily modify the gradle:    

```
// file: node_modules/pushe-react-native/android/build.gradle
// Change
implementation("co.pushe.plus:base:2.4.1-beta05")

// To
implementation("co.pushe.plus:base:2.4.1-beta05") {
     exclude(group:'co.pushe.plus', module:'sentry')
}
```

**Comment by peyman-hakemi** [comment]
ممنون بابت کمکتون من این راه کاری که گفتید رو تست میکنم @mahdi-malv 

کتابخانه ای که باهاش مشکل داریم @mauron85/react-native-background-geolocation هست

**Comment by peyman-hakemi** [comment]
@mahdi-malv
ممنون درست شد
راه حل دایمی تری دارین که اعمال کنم؟

**Comment by peyman-hakemi** [comment]
@mahdi-malv تغییری که گفتین رو انجام دادم
مشکل حل شد
ولی حالا نوتفیکیشن فقط در حالت دیباگ میرسه
ولی تو حالت release نمیرسه

مشکل میدونین برای چیه؟

**Comment by mahdi-malv** [comment]
درود

راه حلی که دادم در بحث ریلیز یا دیباگ بودن دخیل نیست. صرفا یه لایبرری بخاطر کانفلیکت اکسکلود شده.
لطفا بررسی کنید ببینید لاگی چیزی چاپ نمیکنه؟

**Comment by peyman-hakemi** [comment]
سلام
من لاگ گرفتم و 
initialized
registered
برای هر دو false بود
مشکل از چی متونه باشه؟ و چطور میتونم حلش کنم؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود
لطفا لاگ خروجی هنگام لانچ اپ روی دیوایس رو هم بررسی کنید
برای کمک به دیباگ sdk تمام ایونت‌ها رو لاگ میکنه و این لاگ‌ها توسط logcat قابل مشاهده‌ست

```
npx react-native log-android
```

لاگ‌های با تگ  Pushe مرتبط به sdk هستن

</div>

**Comment by peyman-hakemi** [comment]
02-28 11:29:32.874  3508  3537 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.mersasalmand flg=0x4000010 (has extras) } to com.mersamoragheb/co.pushe.plus.datalytics.receivers.AppChangeReceiver

02-28 11:38:12.987  3763  3763 I Pushe   : Starting Pushe initialization

02-28 11:38:13.579  3763  3909 E Pushe   :
02-28 11:38:13.579  3763  3909 E Pushe   : co.pushe.plus.utils.PusheUnhandledException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
02-28 11:38:13.579  3763  3909 E Pushe   :      at co.pushe.plus.m0.c$a.run(Schedulers.kt:4)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
02-28 11:38:13.579  3763  3909 E Pushe   :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-28 11:38:13.579  3763  3909 E Pushe   :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-28 11:38:13.579  3763  3909 E Pushe   :      at java.lang.Thread.run(Thread.java:919)
02-28 11:38:13.579  3763  3909 E Pushe   : Caused by: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
02-28 11:38:13.579  3763  3909 E Pushe   :      at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:150)
02-28 11:38:13.579  3763  3909 E Pushe   :      at androidx.work.WorkManager.getInstance(WorkManager.java:184)
02-28 11:38:13.579  3763  3909 E Pushe   :      at co.pushe.plus.internal.task.TaskScheduler.schedulePeriodicTask(TaskScheduler.kt:180)
02-28 11:38:13.579  3763  3909 E Pushe   :      at co.pushe.plus.internal.task.TaskScheduler.schedulePeriodicTask$default(TaskScheduler.kt:1)
02-28 11:38:13.579  3763  3909 E Pushe   :      at co.pushe.plus.CoreInitializer$a.subscribe(PusheInit.kt:7)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable$IgnoreObservable.onComplete(ObservableIgnoreElementsCompletable.java:66)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.operators.observable.ObservableTake$TakeObserver.onComplete(ObservableTake.java:88)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.operators.observable.ObservableTake$TakeObserver.onNext(ObservableTake.java:66)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
02-28 11:38:13.579  3763  3909 E Pushe   :      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
02-28 11:38:13.579  3763  3909 E Pushe   :      at co.pushe.plus.m0.c$a.run(Schedulers.kt:3)
02-28 11:38:13.579  3763  3909 E Pushe   :      ... 5 more


سلام @mahdi-malv 
این لاگ ها مربوط به اجرای برنامه که با logcat گرفته شد

**Comment by mahdi-malv** [comment]
درود

فکر میکنم این مشکل توی ۲.۴.۳ حل شده باشه
