### ISSUE TITLE
Cannot resolve method 'withAndroidId' in 'UserNotification'

### ISSUE THREAD

**Issue by HoseinAsadi** [pusheco/pushe-react-native#25]
سلام 
هنگام بیلد خطا زیر نشون داده میشه
error: cannot find symbol
                userNotification = UserNotification.withAndroidId(id);
                                                   ^
  symbol:   method withAndroidId(String)
  location: class UserNotification
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

@mahdi-malv 
@amirhaa
@vahid-amintabar

**Comment by zaherii** [comment]
سلام منم همین مشکلو دارم :-(

روی این ورژن 

"pushe-react-native": "^2.4.2",
"react": "^16.13.1",
"react-native": "0.63.4",

**Comment by mahdi-malv** [comment]
درود
ممنون که گفتید

در اسرع وقت بررسی میکنمش

**Comment by mahdi-malv** [comment]
درود مجدد

ممنون میشم نسخه‌ی نهایی رو تست کنید
2.4.3

**Comment by HoseinAsadi** [comment]
سلام توی node ری اکت نیتیو initialize میشه اما برای رجیستر میگه ثبت نشده
است

**Comment by zaherii** [comment]
@mahdi-malv  
درست شد . ممنون

**Comment by mahdi-malv** [comment]
@HoseinAsadi 
رجیستر بحثش مربوط به نیتیو هست که ممکنه دلیل دیگه‌ای داشته باشه
میشه بیشتر شرح بدید که آیا خطایی وجود داره؟
یا توی تیکت یه نمونه از اپ ارسال کنید که من یا همکاران دلیل خطایی که دارید رو بررسی کنن.
