### ISSUE TITLE
 cannot find symbol     co.ronash.pushe.RNPusheNotificationListener.enableNotificationListener(this

### ISSUE THREAD

**Issue by h2soheili** [pusheco/pushe-react-native#3]
example project build failed

```
pushe-react-native-master/example/android/app/src/main/java/com/pushe_demo/MainApplication.java:50: error: cannot find symbol
    co.ronash.pushe.RNPusheNotificationListener.enableNotificationListener(this);
                   ^
  symbol:   class RNPusheNotificationListener
  location: package co.ronash.pushe
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
```

**Comment by mahdi-malv** [comment]
<div dir='rtl'>
سلام
این فایل که در پروژتون پیدا نشده در پلاگین هست:

https://github.com/pusheco/pushe-react-native/blob/master/android/src/main/java/co/ronash/pushe/RNPusheNotificationListener.java

بعد از اینکه پلاگین در npm منتشر شده هنوز این مشکل وجود داره؟

[لینک npm](https://www.npmjs.com/package/pushe-react-native)
</div>

**Comment by amirhaa** [comment]
This issue is related to react native version 1 that is deprecated.
