### ISSUE TITLE
Add support for iOS push

### ISSUE THREAD

**Issue by h2soheili** [pusheco/pushe-react-native#4]

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام
کتابخانه‌ی iOS درحال بازنویسی‌ست و بزودی به پلاگین ری‌اکت نیتیو هم اضافه‌می‌شود.
</div>

**Comment by h2soheili** [comment]
any update about your progress ? 
we already reached production timeline and we prefer to use your services. please tell me your deadline for `ios` support . thanks

**Comment by Hector-Pushe** [comment]
pushe 0.8.3 is released and ready to use in cocoapods for iOS platform. you can read more in:
https://pushe.co/docs/ios

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

پوشه برای iOS منتشرشده و برای برنامه‌های Swift/ObjC قابل‌استفاده است. اما در حال حاضر پلاگین برای ری‌اکت نیتیو طراحی نشده.

در صورتی که آپدیتی در وضعیت رخ‌داد در این issue اطلاع می‌دهم.

**EDIT: 2020**

پوشه در ری‌اکت نیتیو هم از ios پشتیبانی می‌کنه

</div>

**Comment by peyman-hakemi** [comment]
برای استفاده از پوشه در پروژه react native در بخش ios بدون اکانت دولوپری امکان داره؟

**Comment by mahdi-malv** [comment]
@peyman-hakemi 
خیر. اپل دولپر رو ملزم به داشتن اکانت دولوپری کرده
