### ISSUE TITLE
ERROR: Failed to resolve: core

### ISSUE THREAD

**Issue by manvfx** [pusheco/pushe-react-native#5]
Salam
Man pegham in mad k nemizare gradle ra build begire

ERROR: Failed to resolve: core
Affected Modules: pushe-react-native

**Comment by amirhaa** [comment]
<div dir="rtl">

سلام ، لطفا یک بار کش gradle خودتان را پاک کنید و مجددا build (run-android) کنید

برای پاک کردن کش gradle می توانید از [این لینک استفاده کنید](https://stackoverflow.com/a/30450020/8823891)

در ضمن هنگام اجرای دستور build باید وی‌پی‌ان یا ابزار دیگری برای گذر از تحریم داشته باشید

</div>
