### ISSUE TITLE
problem export release android with pushe 

### ISSUE THREAD

**Issue by manvfx** [pusheco/pushe-react-native#6]
> Configure project :pushe-react-native
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.

**Comment by amirhaa** [comment]
<div dir="rtl">
سلام ، این لاگی که گذاشتید صرفا warning و مشکل از چیز دیگه ای می باشد اگه ممکنه کل لاگ را اینجا بذارید

این لاگ در واقع بخاطر کاتلینه و قابل چشم‌پوشیه.
</div>

**Comment by amirhaa** [comment]
<div dir="rtl">
@manvfx 
امکانش هست راجب این مشکل هم بگید که وضعیت چه جوریه و آیا مشکل برطرف شد؟
</div>

**Comment by manvfx** [comment]
آره برطرف شده اما warning هنوز هست که البته مهم نیستش

**Comment by manvfx** [comment]
تشکر از پشتیبانی بسیار سریع و خوبتون

**Comment by manvfx** [comment]
![bug](https://user-images.githubusercontent.com/6747872/66857237-b2c50c80-ef93-11e9-82c5-ef86361f9566.JPG)

در اجرای اپلیکیشنم دچار مشکل هستم

**Comment by manvfx** [comment]
![bug2](https://user-images.githubusercontent.com/6747872/66867700-b6af5980-efa8-11e9-83b4-294a3892f6bd.JPG)

**Comment by amirhaa** [comment]
<div dir="rtl">

در عکس اولی که فرستادید همچنان به autolink داره ارور میده و می گه که یک پلاگین را به صورت دستی لینک کرده اید ، اون را حتما unlink کنید

و راجب ارور دوم ، توی فولدر android در داخل پروژه‌تان درستور زیر را بزنید:

</div>

```
gradlew clean
```

<div dir="rtl">

یا به صورت زیر

</div>

```
./gradlew clean
```

<div dir="rtl">

و در روت پروژه ‌تان مجدد react-native run-android را بزنید

</div>
