### ISSUE TITLE
pushe in react native 0.61.2

### ISSUE THREAD

**Issue by manvfx** [pusheco/pushe-react-native#7]
من از آخرین نسخه ریکت نیتیو استفاده میکنم همانطور که طبق مستندات ریکت هست امکان autolinking وجود داره. فقط نصب کافیه؟ چون وقتی من نه فقط پکیج پوشه پکیج های دیگری هم نصب میکنم به dependency ها اضافه نمیشه و وقتی از react-native link استفاده میکنم ارور دارم. آیا در فایل react-native.conf.js کانفیگ خاضی لازم هست؟

**Comment by amirhaa** [comment]
<div dir="rtl">

autolink زمانی اتفاق میافته که پروژه را ران کنید پس اگه خطا داشته باشید ممکنه که هنوز این اتفاق نیافتاده باشه

راجب کانفیگ فایل هم که توی راهنما خود ری‌اکت به صورت react-native.config.js گذاشته و اینکه آیا توی این کانفیگ دارید کتابخانه پوشه را کاستوم می کنید؟

[لینک autolink برای مطالعه بیشتر](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
)

و اگر با دستور react-native link قبلا پوشه را لینک کرده اید یک بار react-native unlink را بزنید که بشه مجددا از autolink استفاده کرد
</div>

**Comment by manvfx** [comment]
نخیر من توی کانفیگ چیزی از پوشه کانفیگ نکردم

**Comment by manvfx** [comment]
الان همه موارد من بدرستی انجام میشه بدون هیچ خطایی اما الان اپلیکیشنم کا باز میشه صفحه سفید میمونه و هیچ اروری هم نداره.

**Comment by amirhaa** [comment]
<div dir="rtl">

کتابخانه پوشه که صرفا در بکگراند ران می شه و ظاهری نداره که مشاهده کنید و ممکنه مشکل از این باشه که فایل های جاوااسکریپت در فولدر مربوطه در اندروید ریخته نشده باشند (react-native start) ، می تونید از ابزارهای 

[mLogcat](https://mlogcat.tistory.com/) ویا از [pidcat](https://github.com/JakeWharton/pidcat) برای مشاهده لاگ‌های اپ دیباگ‌تان استفاده کنید.

و اینکه اگه دستور ```Pushe.initialize``` را در کدتون قرار داده اید در کنسول ‌تان چک کنید که نصب گرفته اید یا خیر

</div>
