### ISSUE TITLE
ارسال  json به سمت کلایتنت

### ISSUE THREAD

**Issue by psobhanlo** [pusheco/pushe-react-native#8]
تو مواردی ممکنه لازم داشته باشم یه  
یه سری داده از سمت سرور به اپ بفرستم. 
به صورتjson
که مثلا به لیستی داده جدید اضافه کنم.

چطوری میتونم این رو پیاده سازی کنم . یا سمت اپ دریافت کنم این داده های ارسالی 

نمیخوام کاربر متوجه بشه.

**Comment by amirhaa** [comment]
<div dir="rtl">

کتابخانه ری‌اکت‌نیتیو را ما بازنویسی کردیم و الان نسخه آخر با پکیج نیم [pushe-react-native] در [مخزن npm] قابل نصب می باشد ، در این نسخه کالبک های اعلان که قبلا در کتابخانه نیتیو پوشه بود اضافه شده 

راهنما را می تونید در [این آدرس][doc] مشاهده کنید

ضمنا سعی شده که در بازنویسی نسخه جدید backward compatibility رعایت شود و با اندکی تغییرات بشه به این نسخه بروزرسانی کرد

</div>

[pushe-react-native]: https://www.npmjs.com/package/pushe-react-native
[مخزن npm]: https://www.npmjs.com/package/pushe-react-native
[doc]: https://pushe.co/docs/react-native#notification_callbacks

**Comment by psobhanlo** [comment]
واقعا واقعا واقعا این نیاز بودش که باید رفع میشد.

ممنونم از شما بابت این اپدیته
