### ISSUE TITLE
rename react-native-pushe to pushe-react-native in   https://console.pushe.co/applications/guide/android .  (ReactNative)  راهنمای گام به گام ساخت اپلیکیشن

### ISSUE THREAD

**Issue by h2soheili** [pusheco/pushe-react-native#9]
ضافه کردن کتابخانه react native

با استفاده از دستور زیر کتابخانه ی پوشه را به پروژه خود اضافه کنید.
کپی
npm i -P` react-native-pushe`
یا با استفاده از yarn :
کپی
yarn add `react-native-pushe`
برای لینک کردن کتابخانه‌ی پوشه دستور زیر را اجرا کنید:
کپی
react-native link `react-native-pushe`

**Comment by amirhaa** [comment]
This issue is related to react native version 1 that is deprecated.
